userrails/config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get 'sessions/index'

  get 'user/index'
  # get 'user/new'

  # get 'secret/index'

  get 'home/index'
  root 'home#index'

  get '/secret' => 'secret#index'
  get '/signup' => 'user#new'
  post '/users' => 'user#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

userrails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

userrails/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

userrails/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :articles 
  # has_many :articles, dependent: :destroy
end

userrails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

userrails/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authorize
  def new
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    @article.save
    redirect_to @article
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

userrails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

userrails/app/controllers/secret_controller.rb
class SecretController < ApplicationController
  before_action :authorize
  def index
  end
end

userrails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

userrails/app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end



end

userrails/app/helpers/application_helper.rb
module ApplicationHelper
end

userrails/app/helpers/articles_helper.rb
module ArticlesHelper
end

userrails/app/helpers/home_helper.rb
module HomeHelper
end

userrails/app/helpers/secret_helper.rb
module SecretHelper
end

userrails/app/helpers/sessions_helper.rb
module SessionsHelper
end

userrails/app/helpers/user_helper.rb
module UserHelper
end

userrails/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>

  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>

      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>


<%= link_to 'New article', new_article_path %>

userrails/app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

userrails/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %>

userrails/app/views/home/index.html.erb
<h1>HOMEPAGE</h1>

userrails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Userrails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    # added these lines.
    <% if current_user %>
      Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
    <% else %>
      <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
    <% end %>

    <%= yield %>
  </body>
</html>

userrails/app/views/secret/index.html.erb
<h1>Secret#index</h1>
<p>Find me in app/views/secret/index.html.erb</p>

userrails/app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

userrails/app/views/user/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>